packages:
  - 'apps/*'
  - 'libs/*'
  - 'libs/domain/*'
allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  '@swc/core': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  nx: true
  prisma: true
  sharp: true
  unrs-resolver: false
