// Regenerates src/lib/embedded-assets.generated.ts: the Poppins fonts and the
// receipt logo as base64, so the renderer reads no file at runtime and works
// the same under tsx (apps/worker) and the Next.js bundle (apps/api).
//
//   node libs/receipts/scripts/embed-assets.mjs
//
// The logo is `assets/branding/logo-on-light.png` resized to 300 px and
// quantized to 64 colours (scripts/logo-receipt.png).
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);
const font = (weight) =>
  readFileSync(require.resolve(`@fontsource/poppins/files/poppins-latin-${weight}-normal.woff`)).toString('base64');

const body = `// GENERATED by libs/receipts/scripts/embed-assets.mjs -- do not edit by hand.
// Poppins (SIL Open Font License 1.1, via @fontsource/poppins), latin subset.

export const POPPINS_REGULAR_WOFF = '${font(400)}';
export const POPPINS_SEMIBOLD_WOFF = '${font(600)}';
export const RECEIPT_LOGO_PNG = '${readFileSync(join(here, 'logo-receipt.png')).toString('base64')}';
`;
writeFileSync(join(here, '../src/lib/embedded-assets.generated.ts'), body);
