import { execSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';
import { buildOpenApiDocument } from '../apps/api/src/lib/openapi/registry';

const specPath = 'dist/openapi.json';
const typesPath = 'libs/api-client/src/lib/schema.d.ts';

/**
 * Prepended to the file `openapi-typescript` writes, on top of that tool's
 * own generated-file comment. This is deliberately loud and specific (names
 * the source of truth and the regeneration command) rather than trusting a
 * generic "do not edit" banner to be noticed -- see Task 15's ruling that a
 * hand-edit here must be impossible to miss.
 */
const GENERATED_FILE_WARNING = `/**
 * GENERATED FILE -- DO NOT EDIT BY HAND.
 *
 * Generated by \`pnpm api:types\` (tools/generate-api-client.ts) from the
 * OpenAPI document that \`apps/api/src/lib/openapi/registry.ts\` derives from
 * the Zod schemas in \`@rm/contracts\`. Any change made directly to this file
 * is silently discarded the next time someone runs \`pnpm api:types\`.
 *
 * To change these types: change the Zod schema (or the response shape
 * modelled in \`registry.ts\`), then run \`pnpm api:types\` again.
 */
`;

mkdirSync(dirname(specPath), { recursive: true });
writeFileSync(specPath, JSON.stringify(buildOpenApiDocument(), null, 2));

execSync(`pnpm openapi-typescript ${specPath} -o ${typesPath}`, { stdio: 'inherit' });

const generated = readFileSync(typesPath, 'utf8');
writeFileSync(typesPath, GENERATED_FILE_WARNING + generated);

console.log(`Generated ${typesPath}`);
